# -*- coding: utf-8 -*-
"""Exercício1Ebac.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1izrdHOtDBxwUbbtrE3aIewySU54s_-qY
"""

def menu_operacoes():
    print("\nEscolha a operação que deseja realizar:")
    print("1. Adição (+)")
    print("2. Subtração (-)")
    print("3. Multiplicação (*)")
    print("4. Divisão (/)")
    print("5. Sair")

while True:
    num1 = float(input("Digite o primeiro número: "))
    num2 = float(input("Digite o segundo número: "))

    menu_operacoes()
    escolha = input("Digite o número da operação desejada: ")

    # Realizar as operações e exibir o resultado
    if escolha == '1':0
        resultado = num1 + num2
        print(f"Resultado da adição: {resultado}")
    elif escolha == '2':
        resultado = num1 - num2
        print(f"Resultado da subtração: {resultado}")
    elif escolha == '3':
        resultado = num1 * num2
        print(f"Resultado da multiplicação: {resultado}")
    elif escolha == '4':
        if num2 != 0:  # Verificar se o divisor é diferente de zero
            resultado = num1 / num2
            print(f"Resultado da divisão: {resultado}")
        else:
            print("Divisão por zero não é permitida!")
    elif escolha == '5':
        print("Saindo...")
        break
    else:
        print("Escolha inválida, tente novamente.")

        